---
title: "BLOSUM62 project"
author: "Mette Christensen"
date: "12 3 2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Description 
Adding content to Github using git (exercise) using BLOSUM62 data for PCA analysis, using project directory and project script files. Six project script files are constructed:

01_load.R (loading data), 
02_clean.R (for cleaning data - but just passing data on in this setup), 
03_augment.R (for augmenting data -but just passing data on in this setup), 
04.analysis_i.R (data analysis - selecting, augmenting, modelling and visualising data in this setup), 
99_project_functions.R(for function in more than one line of code - not used en this setup), 
00.doit.R (running all project scripts), 

Final result dataframe is shown in results as are final scree and PCA plot

According to Wikipedia: "In bioinformatics, the BLOSUM (BLOcks SUbstitution Matrix) matrix is a substitution matrix used for sequence alignment of proteins. BLOSUM matrices are used to score alignments between evolutionarily divergent protein sequences."

